import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} bg-custom-sea-green flex flex-col`}
      >
        <div className="max-w-[1440px] w-full mx-auto max-sm:p-5 p-[120px] max-xl:p-[60px]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
